version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - platform

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker
